version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80 # changed to 80 https://stackoverflow.com/questions/64723152/wordpress-site-health-the-rest-api-error-loopback-error
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    platform: linux/x86_64 # running on a M1 Mac
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: